Repository openshift/ocm-agent, pull requests merged in 2023-11, with the labels that each got.

#65 Make services CLI flag a list
  pkg/cli/serve/config.go
  pkg/cli/serve/serve.go
  pkg/config/config.go
  pkg/handlers/webhookreceiver.go
  pkg/ocm/connection.go
Labels: lgtm, approved

#64 Add upgrade policies endpoint
  go.mod
  go.sum
  pkg/cli/serve/config.go
  pkg/cli/serve/serve.go
  pkg/config/config.go
  pkg/consts/consts.go
  pkg/handlers/upgrade_policies.go
  pkg/handlers/upgrade_policies_test.go
  pkg/ocm/connection.go
Labels: lgtm, approved

#66 [OSD-19304] - service_log handler for sending requests for a specific cluster to the OCM API
  go.mod
  go.sum
  pkg/consts/test/test.go
  pkg/handlers/helper.go
  pkg/handlers/service_logs.go
  pkg/handlers/service_logs_test.go
  pkg/ocm/connection.go
  pkg/ocm/types.go
Labels: lgtm, approved

#68 OSD-19689: implementing a place holder feature for notifications
  docs/metrics.md
  pkg/consts/test/test.go
  pkg/handlers/helper.go
  pkg/handlers/mocks/service_logs.go
  pkg/handlers/service_logs.go
  pkg/handlers/service_logs_test.go
  pkg/handlers/webhookreceiver.go
  pkg/handlers/webhookreceiver_test.go
  pkg/handlers/webhookrhobsreceiver.go
  pkg/handlers/webhookrhobsreceiver_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: lgtm, approved, jira/valid-reference

#69 OSD-19232 add cluster handler to get cluster object
  pkg/cli/serve/serve.go
  pkg/handlers/cluster.go
  pkg/handlers/cluster_test.go
  pkg/handlers/handlers_common.go
  pkg/handlers/handlers_test.go
  pkg/handlers/upgrade_policies.go
  pkg/handlers/upgrade_policies_test.go
Labels: lgtm, tide/merge-method-squash, approved
